name: inputs
on:
  workflow_dispatch:
    inputs:
      name:
        description: 'Your name'
        required: true
        default: 'World'
      greeting:
        description: 'Greeting message'
        required: true
        default: 'Hello'
jobs:
  greet:
    runs-on: ubuntu-latest
    steps:
      - name: Greet
        run: echo "${{ github.event.inputs.greeting }} ${{ github.event.inputs.name }}!"